// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-build: https://github.com/rdavid/atm/actions/workflows/build.yml/badge.svg
:img-hoc: https://hitsofcode.com/github/rdavid/atm?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/atm?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:url-build: https://github.com/rdavid/atm/actions/workflows/build.yml
:url-cv: http://cv.rabkin.co.il
:url-hoc: https://hitsofcode.com/view/github/rdavid/atm?branch=master
:url-license: https://github.com/rdavid/atm/blob/master/LICENSES/0BSD.txt

= ATM

[subs=attributes+]
++++
<div align="right">
<a href="{url-build}"><img src="{img-build}" alt="build"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/atm" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

Implement a simple ATM (Automated Teller Machine) system.
The system should include 3 components:

* link:include/interface_handler.hpp[User interface]
* link:include/atm_handler.hpp[ATM logic]
* link:include/bank_handler.hpp[Bank communication]

== Description

For maximum responsiveness, communication between these components should be
non-blocking. For example, the `atm_handler` can't call a function of
`user_interface` directly, because doing so would block it from handling
other events.

At start, the system should wait for a card to be inserted. Once the card is
inserted, it then waits for the user to enter their PIN, one digit at a time.
Once enough digits have been entered, the PIN is verified.
If the PIN is not OK, you’re finished, so you return the card to the customer
and resume waiting for someone to enter their card.
If the PIN is OK, you wait for them to either cancel the transaction, display
their balance or withdraw 50.
If they cancel, you’re finished, and you return their card.
If they select to withdraw, you wait for confirmation from the bank before
issuing the cash and returning the card or displaying an “insufficient funds”
message and returning their card.
Every user operation other than the above should be ignored.
Assume a legal PIN is 4 digits long.
Your code should interact with the user and bank using the interfaces in
link:include/interface.hpp[`interface.hpp`] and
link:include/bank.hpp[`bank.hpp`].
link:src/main.cpp[`main.cpp`] will be used to drive the application.

== Example

[,sh]
----
Please enter your card (i)
i
Please enter your PIN (0-9)
3412
PIN incorrect
Ejecting card
Please enter your card (i)
i
Please enter your PIN (0-9)
1234
Withdraw 50? (w)
Display Balance? (b)
Cancel? (c)
w
Issuing 50
b
The balance of your account is 50
c
Cancelled
Ejecting card
Please enter your card (i)
i
Please enter your PIN (0-9)
1234
Withdraw 50? (w)
Display Balance? (b)
Cancel? (c)
b
The balance of your account is 50
q
----

== Implementation details

* You should implement the functions in link:src/driver.cpp[`driver.cpp`]
* You are provided with CMake build scripts but allowed to use any build
system you wish
* Feel free to add member variables and functions to the above classes as you
see fit as well as defining additional types
* Your solution should compile and run without errors
* For bonus points, add unit tests to check your implementation

== License

`ATM` belongs to {url-cv}[David Rabkin] and uses a
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>atm by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/atm" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/atm/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
