# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
version = 1
[[annotations]]
path = [
	"cmake/CompilerWarnings.cmake",
	".gitignore",
	"README.md",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 David Rabkin"
SPDX-License-Identifier = "0BSD"
