# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: build
'on':
  pull_request:
    paths: &paths
      - CMakeLists.txt
      - cmake/**
      - include/**
      - src/**
  push:
    branches: [master]
    paths: *paths
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build
